### ISSUE TITLE
[Enhancement] 考虑save/load支持分part卷

### ISSUE THREAD

**Issue by Jason-ZW** [cnrancher/image-tools#5]
随着支持多架构离线镜像，对应的镜像包大小也跟随上涨。从SE侧了解到，现在离线包的主要传输媒介仍然是U盘，尽管部分SE有大容量U盘但是还是需要支持下小容量U盘传输介质的场景。考虑save/load支持分part？

**Comment by rootwuj** [comment]
版本：v1.3.0-rc4

验证通过。此版本已经支持分卷压缩。

1. 执行save命令时设置`-part -part-size=xx`参数，会按指定卷大小进行压缩。
```
./image-tools save -f ./rancher-images.txt -d saved-images.tar.gz -j 20 -part -part-size=5G

13:11:12 [INFO] Compressing saved-images.tar.gz...
13:11:12 [INFO] Create "saved-images.tar.gz.part0"
13:12:07 [INFO] Create "saved-images.tar.gz.part1"
13:13:30 [INFO] Create "saved-images.tar.gz.part2"
13:14:50 [INFO] Create "saved-images.tar.gz.part3"
13:16:12 [INFO] Create "saved-images.tar.gz.part4"
13:17:20 [INFO] Saved images into "saved-images.tar.gz"
```
2. 直接执行load命令可以正常推送镜像到私有仓库。
3. 将卷解压后，执行load命令配合`-compress=dir`参数，从解压后的缓存文件夹中加载镜像上传至私有仓库。
```
# 使用以下命令一键解压
cat ./saved-images.tar.gz.part* | tar -zxv

./image-tools load -s ./saved-image-cache -compress=dir -d private.registry.io -repo-type=harbor -default-project=library -j 20 
```

**Comment by rootwuj** [comment]
## 补充：默认方式和分卷方式性能对比

版本：v1.3.0-rc4
环境：参考

### 测试内容：
1. 使用默认方式save load镜像，分别验证gzip/zstd压缩方式。
2. 使用分卷方式save load镜像，分别验证gzip/zstd压缩方式。


### 命令：
```
# save
## 压缩 gzip
./image-tools save -f ./rancher-images.txt -d saved-images.tar.gz -j 20 -part -part-size=5G

## 压缩 zstd
./image-tools save -f ./rancher-images.txt -compress=zstd -d saved-images.tar.zstd -j 20 -part -part-size=5G
```

### 测试结果：

save过程：

方式 | 压缩方式 | 总时间 | save镜像 | 打包 | 包大小 | 磁盘总使用量
-- | -- | -- | -- | -- | -- | --
默认 | gzip | 10分54秒 | 4分45秒 | 6分09秒 | 25G | 51G   </br>  25G saved-images.tar.gz  </br>   25G saved-image-cache
分part(5G) | gzip | 10分04秒 | 3分56秒 | 6分08秒 | 24.6G | 51G   </br>  25G saved-image-cache  </br>   5.1G	saved-images.tar.gz.part0   </br>  5.1G	saved-images.tar.gz.part1  </br>  5.1G	saved-images.tar.gz.part2    </br> 5.1G	saved-images.tar.gz.part3    </br> 4.2G	saved-images.tar.gz.part4
默认 | zstd | 13分09秒 | 4分18秒 | 8分51秒 | 25G | 51G   </br>  25G saved-images.tar.zstd  </br>   25G saved-image-cache
分part(5G) | zstd | 12分49秒 | 3分57秒 | 8分52秒 | 24.5G | 51G </br>    25G saved-image-cache  </br>   5.1G	saved-images.tar.zstd.part0   </br>  5.1G	saved-images.tar.zstd.part1  </br>   5.1G	saved-images.tar.zstd.part2  </br>   5.1G	saved-images.tar.zstd.part3  </br>   4.1G	saved-images.tar.zstd.part4

load过程：

方式 | 压缩方式 | 总时间 | 解压缩 | 推送镜像
-- | -- | -- | -- | --
默认 | gzip | 13分50秒 | 6分24秒 | 7分26秒
分part(5G)：直接load | gzip | 13分54秒 | 6分24秒 | 7分30秒
默认 | zstd | 11分53秒 | 6分33秒 | 5分20秒
分part(5G)：直接load | zstd | 14分8秒 | 6分32秒 | 7分36秒
默认 | dir | 7分49秒 | 不需要 | 7分49秒
分part：解压后load（gzip） | dir | 7分45秒 | 不需要 | 7分45秒


### 结果分析：
默认方式和分卷方式，save和load时间基本一致。此功能对性能没有影响。
