### ISSUE TITLE
[feature] Generate image-list file by KDM and RPM GC charts

### ISSUE THREAD

**Issue by STARRY-S** [cnrancher/image-tools#7]
根据 KDM 的 `data.json` 以及 RPM GC 使用的 charts 生成一份镜像列表，列表格式与 Save 命令支持的列表格式一致 （`rancher-images.txt`）。

- RPM 版本: `2.5.X-2.7.X`。
- 工具可以自动根据 Rancher 版本号获取 KDM `data.json`，或通过命令行参数以文件路径或 URL 链接的方式传输至工具中。
- 工具可以自动根据 Rancher 版本号克隆 chart 仓库到本地，或通过命令行参数指定多个已克隆到本地的 chart 仓库的路径。

------

Generate an image list from KDM `data.json` and chart repos used by Rancher Prime, the output image-list format should as same as `rancher-images.txt`.

- RPM versions: `2.5.X-2.7.X`.
- Get KDM `data.json` file by Rancher version automatically, or specify the KDM data file/URL by command line parameter.
- Clone chart repos into local dir by Rancher version automatically, or specify the multiple cloned chart repos by command line parameter.

----

KDM: https://github.com/rancher/kontainer-driver-metadata
Code position of generate image-list: https://github.com/rancher/rancher/blob/release/v2.7/pkg/image/export/main.go#L21

**Comment by STARRY-S** [comment]
The `generate-list` subcommand is available to test in version `v1.4.0-rc2`.

Docs: https://github.com/cnrancher/image-tools/blob/dev/docs/zh_CN/generate-list.md

**Comment by rootwuj** [comment]
Vsersion: v1.4.0-rc3

Verification passed:

1. The image list has been successfully generated based on the KDM data.json and charts, and the data in the list is accurate.
2. All supported parameters of the command to generate-list have been verified and their functionality is correct. For more detailed test results, please refer to the [test cases](https://mysuse.sharepoint.com/:x:/s/QAEngineer/EUSB70ehHR5OvHs2q-1ahJsBrhqVEpixwV4-1oDlztjcrw?e=joeQr8).
